### ISSUE TITLE
looming pull request ahead :)

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/Unified-Multilanguage-Reader#106]
you guys are 96 commits ahead of master. 
maybe it's time for a pull request :)

<img width="409" alt="screenshot 2017-05-12 14 56 50" src="https://cloud.githubusercontent.com/assets/464519/25998913/66410ca4-3723-11e7-81ab-ab316eb97995.png">

**Comment by DanChirtoaca** [comment]
We are preparing for one just now :)

**Comment by mircealungu** [comment]
man, guys, i'm in a meeting which is all about talking about stuff. i envy you when i see your commits :))
