### ISSUE TITLE
pushed to master

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/Unified-Multilanguage-Reader#120]
@Lukeslux @DanChirtoaca 

I apologize, i was meaning to create a pull request to you, so you can review the code, but by mistake I've committed to the reader instead. 

If you look at: https://github.com/mircealungu/Unified-Multilanguage-Reader/commit/fc4f70975102422fc9f19014d5243ea25f08e023

you will see that I've modified a bit the structure of the project in order to: 
- define an umr module that can be installed via `python setup.py install/develop`  (https://github.com/mircealungu/Unified-Multilanguage-Reader/blob/master/src/setup.py) 
- make the module export the `umrblue` blueprint (https://github.com/mircealungu/Unified-Multilanguage-Reader/blob/master/src/umr/__init__.py) which can be nicely integrated in another application. 

the cool thing about this is that, on the server now, we can include the `umrblue` blueprint in the zeeguu application like this: 

```
from umr import umrblue
app.register_blueprint(umrblue, url_prefix="/read")

```
while keeping the zeeguu_umr in its own folder, with its own versioning system.

**Comment by Lukeslux** [comment]
Note to self: need to fix broken references in scrips
