### ISSUE TITLE
page title

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/Unified-Multilanguage-Reader#121]
should be more expressive than Zeeguu UMR...

<img width="300" alt="screenshot 2017-05-21 15 39 58" src="https://cloud.githubusercontent.com/assets/464519/26284454/f441162e-3e3b-11e7-914a-7caad414cbc7.png">

Possibly: 
- Newsroom
- International Newsroom
- Multilanguage Newsroom
- Polyglot Newsroom
- Zeeguu Newsroom

But other ideas could also work.

**Comment by Lukeslux** [comment]
Title has been renamed to 'Zeeguu Reader'.
