### ISSUE TITLE
/ path errors

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/Unified-Multilanguage-Reader#122]
i've installed the UMR blueprint with the prefix `read` on the site: 

   https://www.zeeguu.unibe.ch/read/articles

i don't like now that 

   https://www.zeeguu.unibe.ch/read/

raises a 404. 

should we add the redirect: ?
    
    / -> /articles 

we could also setup the articles back at / but i'm thinking, that maybe in the future we'll find something else to read, e.g. 
    https://www.gutenberg.org/browse/languages/nl

**Comment by Lukeslux** [comment]
In deveopment,  / already points to articles

**Comment by Lukeslux** [comment]
Ah, I now see you moved is back.

**Comment by Lukeslux** [comment]
If we find something else to read, we can  always move then endpoint then, right? In my opinion, it's more logical to have `/articles` at root at this point in time (it's not an expensive operation to move it when desired later in development).

**Comment by mircealungu** [comment]
So then do you want to redirect from / to /articles, or you prefer to put
the articles under /? Any of the two is ok. I just don't think we should
have a 404 on /.

**Comment by Lukeslux** [comment]
Moved it back to `/`. Should be fixed in development now.
