### ISSUE TITLE
Send preferred translation back to Zeeguu.

### ISSUE THREAD

**Issue by Lukeslux** [mircealungu/Unified-Multilanguage-Reader#13]
Should be a simple call back to the api.

**Comment by Lukeslux** [comment]
In addition: this should be moved to be a named function.

**Comment by DanChirtoaca** [comment]
@mircealungu 
In order to send the preferred translation back to Zeeguu, is there an endpoint that achieves that (I can't seem to identify it) or else, how is this designed to happen?

**Comment by mircealungu** [comment]
There is an api (add_translation / delete_translation)
but I think this API will change in the future so
let's postpone this for later.
