### ISSUE TITLE
Preserve current translation until new (extended) translation arrives, when merging

### ISSUE THREAD

**Issue by DanChirtoaca** [mircealungu/Unified-Multilanguage-Reader#139]
Translating multiple consecutive words keeps on emptying the translation bubble and filling it up with the newer translation, which in turn makes the text move left and right, behavior which could become annoying. Thus we might want to preserve the current translation text until the new one arrives. This will ensure that text only expands, to the right.

**Comment by mircealungu** [comment]
niiice!
