### ISSUE TITLE
when redirecting to login, use the ?next=https://www.zeeguu.unibe.ch/read/

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/Unified-Multilanguage-Reader#152]
this way after login the user is sent back to the reader.

**Comment by Lukeslux** [comment]
Fixed in release 0.5 now, made it a bit more flexible:
`'?next=' + request.url`
That way we do not have to manually update it when the url changes, and an article will also redirect properly back to itself after logging in.

**Comment by mircealungu** [comment]
nice!
