### ISSUE TITLE
Test French sources

### ISSUE THREAD

**Issue by Lukeslux** [mircealungu/Unified-Multilanguage-Reader#161]
Ordered from easy to difficult:

- [x] http://www.1jour1actu.com/
- [x] http://www.okapi.fr/
- [x] http://www.phosphore.com/
- [x] https://www.marianne.net/
- [x] http://www.parismatch.com/
- [x] http://www.liberation.fr/ :x: - Does not extract content very well.
- [x] http://www.leparisien.fr/
- [x] http://www.lefigaro.fr/
- [x] http://www.lemonde.fr/

**Comment by mircealungu** [comment]
whoa! you can click in there! i've just tested 1jour1actu and it works.

**Comment by Lukeslux** [comment]
Tested the other sources, only one that does not work perfectly (I labeled it).
