### ISSUE TITLE
two black arrows

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/Unified-Multilanguage-Reader#169]
are one too many. 
maybe make the undo be greyed out as the icon near it? 

![unnamed](https://cloud.githubusercontent.com/assets/464519/26610303/0df27f78-45a7-11e7-8bb9-ec619a67f870.png)

**Comment by DanChirtoaca** [comment]
Easily can be changed, but that will turn off the button animation 'onClick'. Maybe a different kind of icon?

**Comment by DanChirtoaca** [comment]
nevermind, made it gray
