### ISSUE TITLE
iOS seems to not merge words

### ISSUE THREAD

**Issue by Lukeslux** [mircealungu/Unified-Multilanguage-Reader#18]
Neither on Chrome or Safari.

**Comment by mircealungu** [comment]
Could you fix this one?

**Comment by Lukeslux** [comment]
We should have. That is the reason we closed it.
We tested it on an Ipad and modern Mac machine.

**Comment by Lukeslux** [comment]
After refreshing your cache (no old javascript and such), does the problem still occur? It will simply not merge words? On what device and browser?

**Comment by mircealungu** [comment]
Works now!
But there's an distracting flickering of the entire text block every time I
click on a word.
Any idea of what that could be?



On Thu, Feb 23, 2017 at 5:13 PM, Luc van den Brand <notifications@github.com

**Comment by Lukeslux** [comment]
It seems to be an actual feature of iOS, a black box it shortly puts over clickable items..
I don't truly know why it exists, but simple line of css removed it.
If you check heroku now, it should be fixed (when refreshing your cache).

**Comment by mircealungu** [comment]
Indeed! I just tested it and works quite nice!
