### ISSUE TITLE
context is submitted buggy when user uploads translation

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/Unified-Multilanguage-Reader#192]
the translation is inserted in the context, like in the following example

<img width="1148" alt="screenshot 2017-06-06 02 30 48" src="https://cloud.githubusercontent.com/assets/464519/26808859/3e4eab52-4a60-11e7-8762-025734432b76.png">

**Comment by DanChirtoaca** [comment]
@mircealungu Do you maybe know how to reproduce this (what article it was and what paragraph)? On our side, a translation is never appearing in the text itself, it is appended as an html tag attribute. I did have a look at what context we are supplying and it appears to be the correct one, thus my question would be, is there anything else happening to the context that we are supplying to zeeguu, before it is displayed there?
