### ISSUE TITLE
flickering on the phone

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/Unified-Multilanguage-Reader#200]
since this evening I observer a flickering on the phone, every time i select a word to get a translation. 

more precisely, at the moment of the touch, the entire paragraph is highlighted in blue. 

do you have any hunch what could be the problem?

**Comment by mircealungu** [comment]
what was the problem here?

**Comment by Lukeslux** [comment]
```
*
{
  -webkit-backface-visibility:  hidden;
  -webkit-tap-highlight-color:  transparent;
}
```
Solved the issue. We're hiding the tap flicker that's default (also on android now?) on the phone more aggressively.

**Comment by mircealungu** [comment]
you guys have so much more knowledge about browser behavior than I do!! cool.
