### ISSUE TITLE
More specific article difficulty.

### ISSUE THREAD

**Issue by Lukeslux** [mircealungu/Unified-Multilanguage-Reader#23]
Maybe just the number (scaled from 0 to 10?), the color could still be bound to the 'easy', 'medium', 'hard' division such that a simple glance is still possible.

**Comment by mircealungu** [comment]
Nice! Keep the color. And scale the difficulty from 0 to 100!

**Comment by mircealungu** [comment]
Or from 1 to 10 but keep one significant digit. That could be even nicer!

**Comment by Lukeslux** [comment]
How about now?

**Comment by mircealungu** [comment]
Eheh. Nice :)
