### ISSUE TITLE
too much movement with the title becoming bold on mouse over

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/Unified-Multilanguage-Reader#239]
don't you think? 

i usually scan with both my eyes and the mouse. 
however, when the mouse is over the text becomes bold, and jumps a bit to the right, so it perturbes my reading.  

can we find something else? alternatives that i would personally prefer: 
- highlighting the entire article block background with a highlight color
- underline the title (but that would make it look like it's only about the title, and it's not true -- the selection is about the entire article)

**Comment by Lukeslux** [comment]
Changing the background color looked a bit odd in our experience. It's now solved by putting the hovered article into focus and dropping a larger shadow, without changing any scale.

**Comment by mircealungu** [comment]
this sounds really cool.
looking forward to trying it out!
