### ISSUE TITLE
Endpoint for embedding in the zeeguu homepage

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/Unified-Multilanguage-Reader#24]
I was looking today into integrating the news reader in the main site.

The first problem we have to solve is to allow the user who is logged in to the main site to not need to login again to the UMR. 

To do this, I think the easiest way is that you provide an endpoint which can take the session as an GET or POST parameter. 

The second problem is to see how do we make the integration more visually appealing :)

<img width="1431" alt="screenshot 2017-03-12 20 10 45" src="https://cloud.githubusercontent.com/assets/464519/23835016/2e5d9f3e-0760-11e7-8689-080f43310fda.png">

**Comment by Lukeslux** [comment]
We could also require every endpoint in our system to require the session as a GET parameter? In the same manner all Zeeguu endpoints are tagged with an @with_session parameter?
This might be more consistent, and we could still leave a simple login endpoint for debugging purposes.

**Comment by Lukeslux** [comment]
We should probably discuss the stylistic integration on a whiteboard sometime, it's not so easy to discuss design choices in text ;)

**Comment by mircealungu** [comment]
Yes, every endpoint requiring the session in a GET parameter would work.
But then we have to move the reader on the zeeguu server, which serves
everything over SSL. Otherwise the session travels in clear, and that's not
cool.

**Comment by Lukeslux** [comment]
I understand your point. We'll try to add an additional endpoint.

**Comment by mircealungu** [comment]
I'm not sure that adding a new endpoint is the solution. I think the solution is: 

> We could also have every endpoint in our system require the session as a GET parameter? In the same manner all Zeeguu endpoints are tagged with an @with_session parameter?


Maybe we should discuss this in person :)
