### ISSUE TITLE
open specific article

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/Unified-Multilanguage-Reader#26]
one thing that would be cool would be having an endpoint that would create a reader page for a given url. e.g. 

    zeeguu-umr.heroku.com/article/url=... 

this would allow a reader to re-open an article in the reader, while for example, he is browsing his past reading history.

**Comment by Lukeslux** [comment]
Technically, we used to have this feature, as article retrieval was simply a GET request instead of the POST request it is now (it was easier to handle problematic characters, and hid the back-end from the user nicely). We should be able to revert to that.
