### ISSUE TITLE
Session must not be embedded in webpages

### ISSUE THREAD

**Issue by Lukeslux** [mircealungu/Unified-Multilanguage-Reader#39]
Not particularly a secure solution.

**Comment by mircealungu** [comment]
Maybe we can always rely on the session being in the cookie store? 
That would require an overhaul of the entire API though which relies
on session numbers being always appended as GET params. #mustthink

**Comment by Lukeslux** [comment]
We would then also have to ask the user for cookie permissions, and if they say no (or turned off in their browser): no working application.

**Comment by Lukeslux** [comment]
We could do this:
- Remove the login code from the flask server to a separate javascript page. Thus, a piece of client code is able to retrieve the session, and store it to be used across pages (for example with [this](http://www.thomasfrank.se/sessionvars.html)).
- Have @with_session to redirect to this login page if no session in cookie or post data.
- Now the flask server is not concerned with logging-in, and only contains clean UMR focused endpoints expecting the session as POST or Cookie data (integration without login page thus still possible if the session is already available, either trough a cookie or the Zeeguu Platform).

**Comment by Lukeslux** [comment]
Nvm. We would still have the problem of getting the session from server to the client safely.

**Comment by mircealungu** [comment]
One of the following days we will have to deploy the UMR to the same domain as the Zeeguu account management application. 

In that context I think we should go for the solution with the cookie that keeps track of the session for all the zeeguu related activities (account, umr, exercises). So yes, it's a good idea to: 
- remove the login code from the umr server
- redirect to the main zeeguu login page if no cookie is available

i didn't get your last point.

**Comment by Lukeslux** [comment]
If we use a cookie, then my last point is invalid.

**Comment by Lukeslux** [comment]
We could change the javascript to load the session id from the cookie in a variable, on the load event: that way should require minimal code changes.
