### ISSUE TITLE
Move some python methods to different files

### ISSUE THREAD

**Issue by Lukeslux** [mircealungu/Unified-Multilanguage-Reader#45]
Use blueprints to move get_article to the articles.py file. Seems cleaner that it is located there, some other endpoints (like logging-in and decorators) might benefit from being moved too.

**Comment by Lukeslux** [comment]
@DanChirtoaca This is done right?

**Comment by DanChirtoaca** [comment]
I think so. At this point there isn't much else to do regarding it. Shall I
mark it as done?

On Thu, Apr 27, 2017 at 8:39 AM, Luc van den Brand <notifications@github.com

**Comment by Lukeslux** [comment]
Yes, moving it in the project board to Done will do (keeping eachother up
to date on the sprint's progress), we can close all Done issues after the
sprint then ☺

Op 27 apr. 2017 11:28 schreef "Dan Chirtoaca" <notifications@github.com>:
