### ISSUE TITLE
changing the translation in the reader does not update the server

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/Unified-Multilanguage-Reader#46]
to replicate

1. click on a word that is likely to have multiple translations
2. click on the translation, select another one from the drop-down list. the reader is updated with the new translation
3. go to https://www.zeeguu.unibe.ch/bookmarks to see that the server has not been updated with the new translation and instead still has the original translation

I was sure that at some point the add_new_translation [2] and delete_translation_from [1] endpoints were being used to update the server with the user's choice. Or? 

[1] https://github.com/mircealungu/Zeeguu-API/blob/master/zeeguu_api/api/translate_and_bookmark.py#L150
[2] https://github.com/mircealungu/Zeeguu-API/blob/master/zeeguu_api/api/translate_and_bookmark.py#L130

**Comment by Lukeslux** [comment]
Not a bug, simply/luckily/sadly a non-implemented feature, as described in the duplicate issue #13. 
Two things need to happen:
- [ ] Remove dependency on old deprecated translation endpoint, even though it is nice and fast.
- [ ] In the now neatly named method for setting alternative translations, add a call to [1] and [2].

I was (albeit in small bits) working on other issues, but if you prefer I could halt that and make this the next thing to implement.

**Comment by mircealungu** [comment]
ah! wasn't aware that it's a duplicate! 
no urgency. i just wanted to make sure it's documented. 
take your time, finish what you're working on.
