### ISSUE TITLE
Merge consecutive Zeeguu tags automatically.

### ISSUE THREAD

**Issue by Lukeslux** [mircealungu/Unified-Multilanguage-Reader#5]
Just a simple pass trough the document after each translation should do.

**Comment by mircealungu** [comment]
through the entire document, or maybe radiating away from the place of the click?

**Comment by Lukeslux** [comment]
The latter, you are correct. A simple check around the newly added tag
would suffice.

Op 12 dec. 2016 14:48 schreef "Mircea Filip Lungu" <notifications@github.com
>:

through the entire document, or maybe radiating away from the place of the
click?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mircealungu/Unified-Multilanguage-Reader/issues/5#issuecomment-266434962>,
or mute the thread
