### ISSUE TITLE
Automatic Source Documentation

### ISSUE THREAD

**Issue by Lukeslux** [mircealungu/Unified-Multilanguage-Reader#50]
If we do not generate documentation automatically, I am sure it will always be out-of-date. It will also make our lives easier.
- Documentation of the API:
  - Use [flask-swagger-ui](https://pypi.python.org/pypi/flask-swagger-ui/0.0.3) or switch to [Flask RESTPlus](https://flask-restplus.readthedocs.io/en/stable/) and let it do that for us.
  - Don't do that, and use the [Sphinx](http://www.sphinx-doc.org/en/stable/) documentation generator. In that case we can have the API doc in a /docs folder of the repo.
- Documentation of the source.
  - The above mentioned Sphinx might still be useful.
  - It would be really cool if we could do *Continuous Documentation*, where the /docs folder of the repo is automatically updated when something is pushed to the branch (or when CI tests pass). 
    - Would need a running server with web-hooks to the repository.
  - Graph generation is something to look into.

**Comment by Lukeslux** [comment]
Created a documentation branch, the contents are available [here](https://mircealungu.github.io/Unified-Multilanguage-Reader/). Where the branch name is gh-pages.

**Comment by mircealungu** [comment]
I like the concept of Continuous Documentation :)

**Comment by mircealungu** [comment]
For the UMR, the documentation regarding REST endpoints is not the most heavy it seems to me. Rather the Javascript is where there's more know-how. So we have to think about what's the best way to provide documentation for that too.

**Comment by Lukeslux** [comment]
I agree. Looking into javascript documentation tools, do you have any suggestions?
Looking into [esdoc](https://esdoc.org/) right now, which seems the coolest (and most beautiful) one I've encountered thus far.

**Comment by mircealungu** [comment]
documentation coverage :)) 🎉 🎉 🎉
