### ISSUE TITLE
Add Continuous Integration

### ISSUE THREAD

**Issue by Lukeslux** [mircealungu/Unified-Multilanguage-Reader#51]
[Travis CI](https://travis-ci.org) is our best bet.
We would also need to create test-cases, might might be an issue on its own.

**Comment by Lukeslux** [comment]
We should also allow the Heroku server to automatically update itself when development-core is pushed to, we should not need to do this manually.

**Comment by Lukeslux** [comment]
The basic setup for this has been implemented now on branch #51-CI, but I will need either:
- Admin privileges to this repository.
- @mircealungu to enable Travis CI for this repository himself.

Before I can check it out, as otherwise travis cannot be notified with the webhook.

**Comment by mircealungu** [comment]
I've enabled Travis for the repo @Lukeslux
