### ISSUE TITLE
Escaping & character in post request data.

### ISSUE THREAD

**Issue by Lukeslux** [mircealungu/Unified-Multilanguage-Reader#6]
When requesting a translation this can cause problems.

**Comment by mircealungu** [comment]
is this a bug that you found on the server?

**Comment by Lukeslux** [comment]
No ;)
To get a translation we need to send the to-be-translated text to your api
using a POST request. In that request, data is separated with an '&', which
is troublesome if the selected sentence contains this character.
To fix this our code simple needs to convert these characters using their
escaped equivalent before calling zeeguu.

tl;dr; We simply need to fix something small on our side.

Op 12 dec. 2016 14:49 schreef "Mircea Filip Lungu" <notifications@github.com

**Comment by mircealungu** [comment]
but then... shouldn't the tl;dr; be at the top of the message? :)))

**Comment by mircealungu** [comment]
Are you sure this is in the POST request? data separated with & sounds more like GET to me. And in that case, make sure that there is not another endpoint that accepts a GET!

**Comment by Lukeslux** [comment]
Yes, we are sure. POST request also work this way, the information is just not in the URL.
Look at line 65 where data is appended, this is where our bug occurs: https://github.com/mircealungu/Unified-Multilanguage-Reader/blob/development_core/static/scripts/translation.js#L65
