### ISSUE TITLE
Improve JS Documentation coverage

### ISSUE THREAD

**Issue by Lukeslux** [mircealungu/Unified-Multilanguage-Reader#61]
Gotta get that percentage up. The main problem is that tags are missing.

**Comment by mircealungu** [comment]
testing coverage? what tags?

**Comment by Lukeslux** [comment]
This issue is about the documentation coverage, we added comments to all important methods and classes a long time ago, but these do not include JSDoc-like tags like `@param` and `@extends` (as neatly documented by ESDoc [here](https://doc.esdoc.org/github.com/esdoc/esdoc/manual/usage/tags.html).

This results in our documentation coverage being lower than it should be, so would like to fix that ;)

**Comment by Lukeslux** [comment]
@DanChirtoaca Done with the subscription package, documentation coverage is more than 50% now ;)
It's at [this branch](https://github.com/mircealungu/Unified-Multilanguage-Reader/tree/%2361-coverage), that also fixes some issues I created yesterday evening ( #80 and #81 to be precise).
Could you do the translation package's documentation?

**Comment by DanChirtoaca** [comment]
I will do the Translation package ;)!
