### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by DanChirtoaca** [mircealungu/Unified-Multilanguage-Reader#92]
@mircealungu 
![image](https://cloud.githubusercontent.com/assets/17150553/25796444/cc3f3d2a-33d9-11e7-93d8-3a30a888aef5.png)

This error is sometimes thrown when requesting a translation from the Zeeguu server. We are not sure what is the cause for it.

**Comment by mircealungu** [comment]
Is it sometimes, or always when you're testing? Seems to be a cross-origin request, that appears to be sent from 0.0.0.0. to the zeeguu server. It should not happen in production.

**Comment by DanChirtoaca** [comment]
It occurs in strange fashions.  Usually it appears sometimes on some words(this does not mean that if you revisit that article, those particular words still won't be translated). If however we quickly and consecutively try to translate a few words, the chances for it to happen are a lot higher.

Should we then assume that the error is only a side effect of the application being tested in development mode?

**Comment by mircealungu** [comment]
ok, just in case, I've added a dependency to flask-cors and i am allowing now cross-origin requests from anywhere to the API. i wonder if the error goes away now.

**Comment by DanChirtoaca** [comment]
Will update you on this!

**Comment by Lukeslux** [comment]
![image](https://cloud.githubusercontent.com/assets/10974297/26684988/0fb86db6-46e9-11e7-96c3-8cb629990f00.png)
@mircealungu It is happening on zeeguu itself suddenly, I am unable to subscribe to any feed.

**Comment by mircealungu** [comment]
Thanks for the heads up.
Fixed now.

M.

**Comment by DanChirtoaca** [comment]
@mircealungu 
![screenshot from 2017-06-06 20 09 05](https://user-images.githubusercontent.com/17150553/26844559-1b236160-4af4-11e7-836b-574e812e8918.png)

Appears again on the article page..

**Comment by mircealungu** [comment]
Thanks Dan!
There was an error in the translators.
I think it should be fixed by now.

M.
