### ISSUE TITLE
Responsive article list and feed management 

### ISSUE THREAD

**Issue by Lukeslux** [mircealungu/Unified-Multilanguage-Reader#95]
The articles and feeds page work, but they are too tightly coupled to the zeeguu server, not responding when Zeeguu is slow (removing a feed from the list can be instant, as we can do it locally and wait for Zeeguu to catch up). Would need a task queue of some sort though (removing and adding the same feed in succession must happen in the right order)...

Regarding the article list itself, it is currently only possible to request all articles in one go. It would be better to request only a few of them (this requires allot of change on the API side though, @mircealungu ?) , a temporary solution would be to only load one feed's articles when scrolling down far enough (as these _can_ be requested in a piecemeal fashion).

**Comment by DanChirtoaca** [comment]
(Luc) Discussed in meeting, will cache articlelist.
Interesting: http://stackoverflow.com/questions/31266542/storing-css-and-js-in-local-storage

**Comment by mircealungu** [comment]
The localStorage seems to be trivially simple to use.

There is also sessionStorage, which might make even more sense in your context I think. Am I right? 
    https://www.w3schools.com/html/html5_webstorage.asp
